name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x, 26.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Check code style
        run: yarn run format:check
      - name: Build
        run: yarn run build
      - name: Run tests
        run: yarn run coverage
      - name: Validate type definitions
        run: npx check-dts
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          flag-name: ${{ matrix.node-version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
